# simple.gocd.yaml
pipelines:
  Component-A:
    group: Components
    materials:
      mygit:  # this is the name of material
        # says about type of material and url at once
        git: https://github.com/TheProjectAurora/gocd-katas.git
        branch: feature/pipelines
    stages:
      - build: # name of stage
          jobs:
            DockerImage: # name of the job
              elastic_profile_id: "gocd-agent-alpine"
              tasks:
               - exec: # indicates type of task
                   command: /bin/sh
                   arguments:
                    - "-c"
                    - "echo THIS IS Build Image of Component-A"
            DockerHelmChart: # name of the job
              elastic_profile_id: "gocd-agent-alpine"
              tasks:
               - exec: # indicates type of task
                   command: /bin/sh
                   arguments:
                    - "-c"
                    - "echo THIS IS Build Helm Chart of Component-A"
      - test: # name of stage
          jobs:
            TestingComponent: # name of the job
              elastic_profile_id: "gocd-agent-alpine"
              tasks:
               - exec: # indicates type of task
                   command: /bin/sh
                   arguments:
                    - "-c"
                    - "echo THIS IS Test of Component-A"